version: '3.8'

services:
  scraper-presse-citron:
    build: ./News-collector/scraper-presse-citron
    networks:
      - claire-network
    ports:
      - "3001:3000"
    environment: 
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - PGUSER=root
      - PGHOST=claire_postgres
      - PGDATABASE=claire_db
      - PGPASSWORD=root
      - PGPORT=5432
    depends_on:
      - db

  db:
    container_name: claire_postgres
    image: postgres:16
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: claire_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - claire-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d claire_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/var/lib/pgadmin/.pgpass
    networks:
      - claire-network
    depends_on:
      - db

  nocodb:
    container_name: nocodb_container
    image: nocodb/nocodb:latest
    restart: always
    ports:
      - "8081:8080"
    networks:
      - claire-network
    volumes:
      - nocodb_data:/usr/app/data
    depends_on:
      - db

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://root:root@claire_postgres/claire_db
    depends_on:
      - db
    networks:
      - claire-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  n8n:
    container_name: n8n_container
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    networks:
      - claire-network
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=claire_postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=claire_db
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_PASSWORD=root
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_SECURE_COOKIE=true
      - N8N_PROTOCOL=https
      - N8N_ENCRYPTION_KEY=1Sp647NXx/BM71QS3wnlf7FwkA22famKIPulfjS5lQmDL53cSp7d2t7mCDX7jz0f
      - N8N_HOST=n8n.claire-news.tech
      - WEBHOOK_URL=https://n8n.claire-news.tech
      - VUE_APP_URL_BASE_API=https://n8n.claire-news.tech
      - N8N_EDITOR_BASE_URL=https://n8n.claire-news.tech
    volumes:
      - n8n_data:/home/node/.n8
    depends_on:
      - db
  website-capture:
    build: ./News-collector/website-capture
    container_name: website_capture
    networks:
      - claire-network
    ports:
      - "3002:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  claire-network:
    driver: bridge

volumes:
  postgres_data:
  nocodb_data: 
  n8n_data:
